services:
  redis:
    image: redis:8.0
    container_name: redis
    command:
      - redis-server
      - --save
      - "1 1"
      - --dir
      - /data
      - --appendonly
      - "no"
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: always

  postgres:
    image: postgres:18
    container_name: postgres
    environment:
      POSTGRES_USER: admin_identity
      POSTGRES_PASSWORD: admin_identity_123
      POSTGRES_DB: IdentityDb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  redis_data:
    driver: local
  postgres_data: